name: .NET Build

on:
  push:
  pull_request:
    branches: [ main ]
    paths:
    - '**.cs'
    - '**.csproj'

env:
  DOTNET_VERSION: '6.0.401' # The .NET SDK version to use

jobs:
  build:
    name: build-ubuntu-latest
    runs-on: ubuntu-latest
    env: 
      unitTest-directory: UnitTests
      backend-directory: backend-app
      arduino-directory: arduino
      arduinoBuild-directory: arduino/build

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Setup Ninja
      uses: seanmiddleditch/gha-setup-ninja@v4

    - name: Install dependencies
      working-directory: ${{ env.backend-directory }}
      run: dotnet restore
      
    - name: Build
      working-directory: ${{ env.backend-directory }}
      run: dotnet build --configuration Release

    - name: Unit Tests
      working-directory: ${{ env.unitTest-directory }}
      run: dotnet test --verbosity normal
    
    - name: Configure Arduino Simulator
      uses: threeal/cmake-action@v1.3.0
      with:
        source-dir: ${{ env.arduino-directory }}
        build-dir: ${{ env.arduinoBuild-directory }}
        generator: Ninja

    - name: Build Arduino Simulator
      run: cmake --build ${{ env.arduinoBuild-directory }}

    - name: Test API
      run: |
        cd $GITHUB_WORKSPACE/${{ env.backend-directory }}
        pwd
        dotnet run --no-restore --launch-profile api-test &
        cd $GITHUB_WORKSPACE/${{ env.arduinoBuild-directory }}
        pwd
        ./api-test
        killall dotnet

