# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-api:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Setup Ninja
      uses: seanmiddleditch/gha-setup-ninja@v4

    - name: Build Backend Server
      run: |
        cd backend-app
        dotnet build --no-restore

    - name: Build Arduino Simulator
      uses: threeal/cmake-action@v1.3.0
      with:
        source-dir: arduino
        build-dir: arduino/build
        generator: Ninja

    - name: Test API
      run: |
        cd backend-app
        dotnet run --no-restore --launch-profile api-test &
        cd ../arduino/build
        ./api-test
        killall dotnet

